### ISSUE TITLE
All endpoints in one app.js file

### ISSUE THREAD

**Issue by agarwalarjun123** [CodeChefVIT/webinar-flow#11]
Including all endpoints in a single app.js file is not a good practice, include all the endpoints as routes in separate files under the endpoints folder.

**Comment by subhrapaladhi** [comment]
@agarwalarjun123 I will do that asap

**Comment by subhrapaladhi** [comment]
@agarwalarjun123 i have made the required changes. please review it

**Comment by L04DB4L4NC3R** [comment]
approved
